Edits on use of multiple QUIC tunnels subsubsection
obonaventure/draft-quic-atsss-reqs pull request #69
Opened 2020-05-15 13:21 UTC by mirjak

2020-05-15 13:59 UTC, boucadair requested changes

2020-05-15 13:59 UTC, boucadair commented on draft-quic-atsss-reqs.mkd
> +to the ATSSS proxy to transport traffic belowing to one or multiple flows. The UE and ATSSS
```suggestion
to the ATSSS proxy to transport traffic that belongs to one or multiple flows. The UE and ATSSS
```

2020-05-15 13:59 UTC, boucadair commented on draft-quic-atsss-reqs.mkd
> +proxy need to select for each end-to-end data packet one tunnel QUIC connection to forward,
```suggestion
proxy need to select for each application data packet one tunnel QUIC connection to forward,
```

2020-05-15 13:59 UTC, boucadair commented on draft-quic-atsss-reqs.mkd
> +tunnels are used simulateneously for different packets of the same flow.
```suggestion
tunnels are used simultaneously for different packets of the same flow. 
```

2020-05-15 13:59 UTC, boucadair commented on draft-quic-atsss-reqs.mkd
> +Because both QUIC connections are completely indenpdent of each other and the paths on the
```suggestion
Because both (tunnel) QUIC connections are completely independent of each other and the paths on the
```

2020-05-15 13:59 UTC, boucadair commented on draft-quic-atsss-reqs.mkd
> +different access networks usually have different latency, this approach would
```suggestion
different access networks may have different latency, this approach would
```

2020-05-15 13:59 UTC, boucadair commented on draft-quic-atsss-reqs.mkd
> +a split flow. If reordering should be avoided, this would require additional siganaling
```suggestion
a split flow. If reordering should be avoided, this would require additional signaling
```

2020-05-15 13:59 UTC, boucadair commented on draft-quic-atsss-reqs.mkd
> +between the UE and ATSSS, e.g. adding sequence numbers, and a reorder buffer and logic.
```suggestion
between the UE and the ATSSS proxy, e.g., adding sequence numbers, and a reordering buffer and logic.
```

2020-05-18 16:25 UTC, obonaventure approved these changes

2020-05-19 16:22 UTC, merged