Edits to MP-QUIC and TCP over QUIC sections
obonaventure/draft-quic-atsss-reqs pull request #72
Opened 2020-05-15 14:29 UTC by mirjak

2020-05-15 14:59 UTC, boucadair requested changes

2020-05-15 14:59 UTC, boucadair commented on draft-quic-atsss-reqs.mkd
> +{{I-D.ietf-quic-datagram}} can be used. Each data packet would  transported unreliably as a datagram
```suggestion
{{I-D.ietf-quic-datagram}} can be used. Each data packet would be transported unreliably as a datagram
```

2020-05-15 14:59 UTC, boucadair commented on draft-quic-atsss-reqs.mkd
> +over the QUIC connection. Transporting these datagrams unreliably as
```suggestion
over a QUIC connection. Transporting these datagrams unreliably as
```

2020-05-15 14:59 UTC, boucadair commented on draft-quic-atsss-reqs.mkd
> +in IPSec or DTLS tunnels is especially important for flows that do not require reliable delivery
```suggestion
in IPsec or DTLS-based tunnels is especially important for flows that do not require reliable delivery 
```

2020-05-15 14:59 UTC, boucadair commented on draft-quic-atsss-reqs.mkd
> +and suffer from unnecessary delay when reliability is added. QUIC datagram are conngestion controlled,
```suggestion
and suffer from unnecessary delay when reliability is added. QUIC datagrams are congestion-controlled, 
```

2020-05-15 14:59 UTC, boucadair commented on draft-quic-atsss-reqs.mkd
> +this should not impact the end-to-end congestion control negative.
I don't parse this sentence.

2020-05-15 14:59 UTC, boucadair commented on draft-quic-atsss-reqs.mkd
> +Further with splitting traffic can be better distributed based on available ressources
```suggestion
Furthermore, traffic can be better distributed among available paths based on available resources 
```

2020-05-15 14:59 UTC, boucadair commented on draft-quic-atsss-reqs.mkd
> +Another use case in scope for the groups is IP proxying which can be used for tunneling and forwarding of TCP connections.
which "groups"?

2020-05-15 15:22 UTC, mirjak commented on draft-quic-atsss-reqs.mkd
> +this should not impact the end-to-end congestion control negative.
Any better now?

2020-05-19 15:07 UTC, abrunstrom commented on draft-quic-atsss-reqs.mkd
> +
This is quite speculative. What the end-to-end latency is can vary and is in general not known. I would not claim that the cc control loops will not interact.

2020-05-19 16:27 UTC, merged